export { default as Intro } from './Intro'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as FeaturedTours } from './FeaturedTours'
export { default as Places } from './Places'